// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Backend externo compartilhado com o app principal do Ditt.
const SUPABASE_URL = "https://cgsdnvuigolxwzfmnykk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_8--rytxIxWlNNp2T9IUFsw_ems9dlOH";


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storageKey: "ditt-admin-auth",
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: false,
    autoRefreshToken: false,
  }
});

// Limpa qualquer JWT antigo que ficou no localStorage (backend Cloud / sessão anterior).
// Sem isso o supabase-js anexa Bearer inválido em toda chamada → 401 "unrecognized kid".
if (typeof window !== "undefined") {
  try {
    window.localStorage.removeItem("ditt-admin-auth");
    window.localStorage.removeItem("sb-cgsdnvuigolxwzfmnykk-auth-token");
    window.localStorage.removeItem("sb-icxfnkipwcyyeuposgrt-auth-token");
  } catch {}
}
